### ISSUE TITLE
Sync Process

### ISSUE THREAD

**Issue by CleytonBonamigo** [travail/php-Parallel-Prefork#3]
I'm excited to test the script, but before, I need to know if script there is synchronization processes

**Comment by travail** [comment]
Hi @CleytonBonamigo 

First of all what does *synchronization processes* mean? If it points child processes this library spawns, the answer is "no". You can not manage the order in which the child processes work unless you write such an algorithm.
Furthermore this library is to introduce an asynchronous mechanism into your app with *Message Queue* system such as RabbitMQ, Redis or [Q4M](http://q4m.github.io/). This library provides

* Simple prefork server framework.
* Graceful shutdown.
* Run-time reconfiguration.

Thanks.
